/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CardDto {
  columnId: number;
  description: string | null;
  id: number;
  position: number;
  title: string;
}
