/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CardDto } from '../models/card-dto';
export interface ColumnDto {
  cards: Array<CardDto>;
  id: number;
  position: number;
  title: string;
}
