/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardDto } from '../../models/card-dto';

export interface CardControllerRead$Params {

/**
 * Object ID
 */
  id: number;
}

export function cardControllerRead(http: HttpClient, rootUrl: string, params: CardControllerRead$Params, context?: HttpContext): Observable<StrictHttpResponse<CardDto>> {
  const rb = new RequestBuilder(rootUrl, cardControllerRead.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CardDto>;
    })
  );
}

cardControllerRead.PATH = '/api/card/{id}';
