/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';

export interface ColumnControllerGetAll$Params {
}

export function columnControllerGetAll(http: HttpClient, rootUrl: string, params?: ColumnControllerGetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ColumnDto>>> {
  const rb = new RequestBuilder(rootUrl, columnControllerGetAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ColumnDto>>;
    })
  );
}

columnControllerGetAll.PATH = '/api/column/all';
