/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';

export interface ColumnControllerRead$Params {

/**
 * Object ID
 */
  id: number;
}

export function columnControllerRead(http: HttpClient, rootUrl: string, params: ColumnControllerRead$Params, context?: HttpContext): Observable<StrictHttpResponse<ColumnDto>> {
  const rb = new RequestBuilder(rootUrl, columnControllerRead.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColumnDto>;
    })
  );
}

columnControllerRead.PATH = '/api/column/{id}';
