/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';
import { UpdateColumnDto } from '../../models/update-column-dto';

export interface ColumnControllerUpdate$Params {

/**
 * Object ID
 */
  id: number;
      body: UpdateColumnDto
}

export function columnControllerUpdate(http: HttpClient, rootUrl: string, params: ColumnControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ColumnDto>> {
  const rb = new RequestBuilder(rootUrl, columnControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColumnDto>;
    })
  );
}

columnControllerUpdate.PATH = '/api/column/{id}';
