/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';
import { CreateColumnDto } from '../../models/create-column-dto';

export interface ColumnControllerCreate$Params {
      body: CreateColumnDto
}

export function columnControllerCreate(http: HttpClient, rootUrl: string, params: ColumnControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ColumnDto>> {
  const rb = new RequestBuilder(rootUrl, columnControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColumnDto>;
    })
  );
}

columnControllerCreate.PATH = '/api/column/create';
